App_Blog/urls.py
from django.urls import path
from .views import blog_list, blog_detail

app_name = 'App_Blog'

urlpatterns = [
    path('blog/', blog_list, name='blog_list'),
    path('blog/<int:blog_id>/', blog_detail, name='blog_detail'),
]

App_Login/urls.py
from django.urls import path
from .import views

app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/',views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),

]

Travel_Project/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Login.urls')),
    path('',include('App_Content.urls')),
    path('',include('App_Blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=100, blank=True)
    dob = models.DateField(blank=True, null=True)
    facebook = models.URLField(blank=True)
    website = models.URLField(blank=True)

    def __str__(self):
        return str(self.user)

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile


class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(required=True, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, label='',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password Confirmation'}))

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['full_name', 'description', 'dob', 'facebook', 'website']

    widgets = {
        'dob': forms.DateInput(attrs={'type': 'date'}),
        'facebook': forms.URLInput(),
        'website': forms.URLInput(),
    }

App_Login/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from .models import UserProfile
from .forms import CreateNewUser, EditProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# Create your views here.

def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    return render(request, 'App_Login/signup.html', context={'title': 'Sign up', 'form': form})


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Content:home'))

    return render(request, 'App_Login/login.html', context={'title': 'Login', 'form': form})


@login_required
def profile(request):
    return render(request, 'App_Login/profile.html')


@login_required
def edit_profile(request):
    user_profile = request.user.user_profile

    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect(reverse('App_Login:profile'))
    else:
        form = EditProfileForm(instance=user_profile)

    return render(request, 'App_Login/edit_profile.html', {'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))

App_Login/templates/App_Login/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block title_block %} {{ title }} {% endblock %}
{% block body_block %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h1 class="text-center">Edit Your Profile</h1>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.full_name|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                {{ form.description|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                <label>Date of Birth</label>
                                <div class="input-group date" id="dob-datepicker" data-target-input="nearest">
                                    <input type="text" placeholder="YYYY-MM-DD" class="form-control datetimepicker-input" data-target="#dob-datepicker" name="dob"/>
                                    <div class="input-group-append" data-target="#dob-datepicker" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                {{ form.facebook|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                {{ form.website|as_crispy_field }}
                            </div>
                            <button type="submit" class="btn btn-primary">Save Changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(function () {
            $('#dob-datepicker').datetimepicker({
                format: 'YYYY-MM-DD',
                useCurrent: false,
            });
        });
    </script>
{% endblock %}

App_Login/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block title_block %} {{title}} {% endblock %}
{% block body_block %}
    <h1>Log In Your Profile</h1>
    {% block css_block %}
        <style>
            .sign_up {
                width: 550px;
                border: 1px solid #ccc;
                padding: 30px;
            }
            .log_in {
                width: 550px;
                padding: 20px;
                border: 1px solid #ccc;
            }
        </style>
    {% endblock %}
    <center>
        <div class="log_in">
            <form method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" style="width:100%">Log In</button>
            </form>
        </div>
        <br>
        <div class="sign_up">
            <p>Don't have an account? <a href="{% url 'App_Login:sign_up' %}">Sign up</a></p>
        </div>
    </center>
{% endblock %}

App_Login/templates/App_Login/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block title_block %} {{ title }} {% endblock %}
{% block body_block %}
    <h1>View Profile</h1>
    {% block css_block %}{% endblock %}
    <br>
    <p><strong>Username:</strong> {{ user.username }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>Name:</strong> {{ user.user_profile.full_name|default:"Not provided" }}</p>
    <p><strong>Description:</strong> {{ user.user_profile.description|default:"Not provided" }}</p>
    <p><strong>Date of Birth:</strong> {{ user.user_profile.dob|default:"Not provided" }}</p>
    <p><strong>Facebook:</strong> {{ user.user_profile.facebook|default:"Not provided" }}</p>
    <p><strong>Website:</strong> {{ user.user_profile.website|default:"Not provided" }}</p>
    <br>

    <a href="{% url 'App_Login:edit_profile' %}" class="btn btn-primary">Edit Profile</a>

{% endblock %}

App_Login/templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block title_block %} {{title}} {% endblock %}
{% block body_block %}
<h1>sign up page</h1>

    {% block css_block %}
    <style>
        .sign_up {
            width: 550px;
            border: 1px solid #ccc;
            padding: 30px;
        }
        .Log_in {
            width: 550px;
            padding: 20px;
            border: 1px solid #ccc;
        }
    </style>
    {% endblock %}
<center>
    <div class="sign_up">
        <h4>Sign up to see more details</h4>
        <form method="POST">
            {% bootstrap_form form %}
            {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-primary" style="width:100%">Sign up</button>
        </form>
    </div>
    <div class="Log_in">
        <p>Have an account? <a href="{% url 'App_Login:login' %}">Log in</a></p>
    </div>
</center>
{% endblock  %}