App_Blog/urls.py
from django.urls import path
from .views import blog_list, blog_detail

app_name = 'App_Blog'

urlpatterns = [
    path('blog/', blog_list, name='blog_list'),
    path('blog/<int:blog_id>/', blog_detail, name='blog_detail'),
]

App_Content/urls.py
from django.urls import path
from .import views

app_name = "App_Content"

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('my_booking/', views.My_Booking, name='my_booking'),
    path('view_details/<int:destination_id>/', views.view_details, name='view_details'),
    path('search_results/', views.search_results, name='search_results'),

]

App_Login/urls.py
from django.urls import path
from .import views

app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/',views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),

]

Travel_Project/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Login.urls')),
    path('',include('App_Content.urls')),
    path('',include('App_Blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}Antora Tourism BD{% endblock %}</title>

    <!-- Bootstrap Link -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

     <!-- Custom CSS Block -->
    {% block css_block %} {% endblock %}
</head>
<body>
    <!-- Navbar -->
    {% include 'navbar.html' %}

    <!-- Body content -->
    <div class="container-fluid">
        {% block body_block %}
        {% endblock %}
    </div>

    <!-- Footer -->
    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <title>{% block title_block %} Antora Tourism BD {% endblock %}</title>

  {% block css_block %}
  {% endblock %}
</head>
<body>

  <div class="container">
    {% block body_block %}  {% endblock %}
  </div>

  <!-- Fixed Footer Section -->
  <footer class="footer mt-5 p-5 bg-dark text-white">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <h5>Navigation</h5>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Home</a></li>
            <li><a href="#" class="text-white">About Us</a></li>
            <li><a href="#" class="text-white">Services</a></li>
            <!-- Add more navigation links as needed -->
          </ul>

        </div>
        <div class="col-md-3">
          <h5>Contact Us</h5>
          <p>Email: info@example.com</p>
          <p>Phone: +1 (123) 456-7890</p>
        </div>

        <div class="col-md-3 text-right">
          <h5>Follow Us</h5>
          <a href="#" class="text-white"><i class="fa fa-facebook"></i></a>
          <a href="#" class="text-white"><i class="fa fa-twitter"></i></a>
          <a href="#" class="text-white"><i class="fa fa-instagram"></i></a>
        </div>

        <div class="col-md-3">
          <h5>Newsletter</h5>
          <form>
            <div class="form-group">
              <input type="email" class="form-control" placeholder="Enter your email">
            </div>
            <button type="submit" class="btn btn-primary">Subscribe</button>
          </form>
        </div>
      </div>

    <!-- Copyright Section -->
      <div class="row">
        <div class="col-12 text-center">
          <hr class="bg-white">
          <p>&copy; 2023 Antora Tourism BD. All rights reserved.</p>

        </div>
      </div>

    </div>
  </footer>

</body>
</html>

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <title>{% block title_block %} Antora Tourism BD {% endblock %}</title>

  {% block css_block %}
  {% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'App_Content:home' %}">Adventure Ascent BD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!---Navbar Link Section-->

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'App_Content:home' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Blog:blog_list' %}">Blog</a>
        </li>


        {% if user.is_authenticated %}
       <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:profile' %}">Your Profile</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Content:my_booking' %}">My Booking</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Content:contact' %}">Contact</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:logout' %}">Log Out</a>
        </li>

        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:login' %}">LogIn</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:sign_up' %}">Register</a>
        </li>

         <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Content:contact' %}">Contact</a>
        </li>
        {% endif %}

      </ul>

      <!---Navbar Search Section--->
      <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'App_Content:search_results' %}">
        <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search">
        <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <div style="padding-top:20px">
    {% block body_block %}  {% endblock %}
  </div>

</body>
</html>