App_Blog/urls.py
from django.urls import path
from .views import blog_list, blog_detail

app_name = 'App_Blog'

urlpatterns = [
    path('blog/', blog_list, name='blog_list'),
    path('blog/<int:blog_id>/', blog_detail, name='blog_detail'),
]

Travel_Project/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Login.urls')),
    path('',include('App_Content.urls')),
    path('',include('App_Blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    blog_title = models.CharField(max_length=264, verbose_name='Put on a Title')
    blog_content = models.TextField(verbose_name='what is on your mind')
    blog_image = models.ImageField(upload_to='blog_images',verbose_name='Image')
    publish_date = models.DateField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-publish_date',]
    def __str__(self):
        return self.blog_title

App_Blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def blog_list(request):
    # Retrieve all blog posts from the database
    blogs = Blog.objects.all()

    # Pass the list of blog posts to the template
    return render(request, 'App_Blog/blog_list.html', {'blogs': blogs})

def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)

    # Pass the blog post to the template
    return render(request, 'App_Blog/blog_details.html', {'blog': blog})

App_Blog/templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container mt-5">
    <h1>{{ blog.blog_title }}</h1>
    <p class="text-muted">Published on {{ blog.publish_date }}</p>
    <img src="{{ blog.blog_image.url }}" class="img-fluid mb-3" alt="{{ blog.blog_title }}">
    <p>{{ blog.blog_content }}</p>
    <a href="{% url 'App_Blog:blog_list' %}" class="btn btn-secondary">Back to Blog List</a>
  </div>
{% endblock %}

App_Blog/templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% block body_block %}
<h1>View Blogs</h1>
  <div class="container mt-5">
    <h1>Blog List</h1>
    {% for blog in blogs %}
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">{{ blog.blog_title }}</h5>
          <p class="card-text">{{ blog.blog_content|truncatewords:30 }}</p>
          <a href="{% url 'App_Blog:blog_detail' blog_id=blog.id %}" class="btn btn-primary">Read More</a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}